default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: "1234"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Eyeris_development

test:
  <<: *default
  database: Eyeris_test

production:
  <<: *default
  database: Eyeris_production
  username: Eyeris
  password: <%= ENV["EYERIS_DATABASE_PASSWORD"] %>
